# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mkDodo1 <- function(a, b) {
    .Call(`_introRcppObjets_mkDodo1`, a, b)
}

mkDodo2 <- function(a, b) {
    .Call(`_introRcppObjets_mkDodo2`, a, b)
}

printDodo1 <- function(xpDodo) {
    invisible(.Call(`_introRcppObjets_printDodo1`, xpDodo))
}

printDodo2 <- function(xpDodo) {
    invisible(.Call(`_introRcppObjets_printDodo2`, xpDodo))
}

mkRDV <- function(lieu, h, m, s) {
    .Call(`_introRcppObjets_mkRDV`, lieu, h, m, s)
}

getLieu <- function(xpRDV) {
    .Call(`_introRcppObjets_getLieu`, xpRDV)
}

getHeure <- function(xpRDV) {
    .Call(`_introRcppObjets_getHeure`, xpRDV)
}

testHeure <- function() {
    invisible(.Call(`_introRcppObjets_testHeure`))
}

testHeureAddition <- function() {
    invisible(.Call(`_introRcppObjets_testHeureAddition`))
}

demoRDV <- function() {
    invisible(.Call(`_introRcppObjets_demoRDV`))
}

demoTuple <- function() {
    invisible(.Call(`_introRcppObjets_demoTuple`))
}

dodo_boucle <- function() {
    invisible(.Call(`_introRcppObjets_dodo_boucle`))
}

dodo_construit_detruit <- function() {
    invisible(.Call(`_introRcppObjets_dodo_construit_detruit`))
}

dodo_copie_reference <- function() {
    invisible(.Call(`_introRcppObjets_dodo_copie_reference`))
}

dodo_move <- function() {
    invisible(.Call(`_introRcppObjets_dodo_move`))
}

dodo_shared_ptrs <- function() {
    invisible(.Call(`_introRcppObjets_dodo_shared_ptrs`))
}

dodo_vecteur <- function() {
    invisible(.Call(`_introRcppObjets_dodo_vecteur`))
}

dodo_vecteur2 <- function() {
    invisible(.Call(`_introRcppObjets_dodo_vecteur2`))
}

